/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// AirShoppingPayload is the type for AirShopping endpoint request body
    /// </summary>
    [DataContract]
    public partial class AirShoppingPayload : IEquatable<AirShoppingPayload>
    { 
        /// <summary>
        /// Corporate Discount Codes Map
        /// </summary>
        /// <value>Corporate Discount Codes Map</value>

        [DataMember(Name="corporateDiscountCodes")]
        public Object CorporateDiscountCodes { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>

        [DataMember(Name="metadata")]
        public Metadata Metadata { get; set; }

        /// <summary>
        /// Origin/Destination pair in a shopping search scenario
        /// </summary>
        /// <value>Origin/Destination pair in a shopping search scenario</value>
        [Required]
        
        [DataMember(Name="originDestinations")]
        public List<OriginDestinationASRQ> OriginDestinations { get; set; }

        /// <summary>
        /// Gets or Sets Preferences
        /// </summary>

        [DataMember(Name="preferences")]
        public Preferences Preferences { get; set; }

        /// <summary>
        /// Gets or Sets Travelers
        /// </summary>
        [Required]
        
        [DataMember(Name="travelers")]
        public Travelers Travelers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AirShoppingPayload {\n");
            sb.Append("  CorporateDiscountCodes: ").Append(CorporateDiscountCodes).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  OriginDestinations: ").Append(OriginDestinations).Append("\n");
            sb.Append("  Preferences: ").Append(Preferences).Append("\n");
            sb.Append("  Travelers: ").Append(Travelers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AirShoppingPayload)obj);
        }

        /// <summary>
        /// Returns true if AirShoppingPayload instances are equal
        /// </summary>
        /// <param name="other">Instance of AirShoppingPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AirShoppingPayload other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CorporateDiscountCodes == other.CorporateDiscountCodes ||
                    CorporateDiscountCodes != null &&
                    CorporateDiscountCodes.Equals(other.CorporateDiscountCodes)
                ) && 
                (
                    Metadata == other.Metadata ||
                    Metadata != null &&
                    Metadata.Equals(other.Metadata)
                ) && 
                (
                    OriginDestinations == other.OriginDestinations ||
                    OriginDestinations != null &&
                    OriginDestinations.SequenceEqual(other.OriginDestinations)
                ) && 
                (
                    Preferences == other.Preferences ||
                    Preferences != null &&
                    Preferences.Equals(other.Preferences)
                ) && 
                (
                    Travelers == other.Travelers ||
                    Travelers != null &&
                    Travelers.Equals(other.Travelers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CorporateDiscountCodes != null)
                    hashCode = hashCode * 59 + CorporateDiscountCodes.GetHashCode();
                    if (Metadata != null)
                    hashCode = hashCode * 59 + Metadata.GetHashCode();
                    if (OriginDestinations != null)
                    hashCode = hashCode * 59 + OriginDestinations.GetHashCode();
                    if (Preferences != null)
                    hashCode = hashCode * 59 + Preferences.GetHashCode();
                    if (Travelers != null)
                    hashCode = hashCode * 59 + Travelers.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AirShoppingPayload left, AirShoppingPayload right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AirShoppingPayload left, AirShoppingPayload right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
