/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BaggageAllowanceItem : IEquatable<BaggageAllowanceItem>
    { 
        /// <summary>
        /// Options choose type, possible values are: one - select one of suggested options; many - select multiple suggested options
        /// </summary>
        /// <value>Options choose type, possible values are: one - select one of suggested options; many - select multiple suggested options</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ChooseTypeEnum
        {
            
            /// <summary>
            /// Enum OneEnum for one
            /// </summary>
            [EnumMember(Value = "one")]
            OneEnum = 1,
            
            /// <summary>
            /// Enum ManyEnum for many
            /// </summary>
            [EnumMember(Value = "many")]
            ManyEnum = 2
        }

        /// <summary>
        /// Options choose type, possible values are: one - select one of suggested options; many - select multiple suggested options
        /// </summary>
        /// <value>Options choose type, possible values are: one - select one of suggested options; many - select multiple suggested options</value>

        [DataMember(Name="chooseType")]
        public ChooseTypeEnum? ChooseType { get; set; }

        /// <summary>
        /// options to choose
        /// </summary>
        /// <value>options to choose</value>

        [DataMember(Name="options")]
        public List<BaggageAllowanceItemOption> Options { get; set; }

        /// <summary>
        /// Passenger references that access this baggage condition
        /// </summary>
        /// <value>Passenger references that access this baggage condition</value>

        [DataMember(Name="passengerRefs")]
        public string PassengerRefs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BaggageAllowanceItem {\n");
            sb.Append("  ChooseType: ").Append(ChooseType).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  PassengerRefs: ").Append(PassengerRefs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BaggageAllowanceItem)obj);
        }

        /// <summary>
        /// Returns true if BaggageAllowanceItem instances are equal
        /// </summary>
        /// <param name="other">Instance of BaggageAllowanceItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BaggageAllowanceItem other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ChooseType == other.ChooseType ||
                    ChooseType != null &&
                    ChooseType.Equals(other.ChooseType)
                ) && 
                (
                    Options == other.Options ||
                    Options != null &&
                    Options.SequenceEqual(other.Options)
                ) && 
                (
                    PassengerRefs == other.PassengerRefs ||
                    PassengerRefs != null &&
                    PassengerRefs.Equals(other.PassengerRefs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ChooseType != null)
                    hashCode = hashCode * 59 + ChooseType.GetHashCode();
                    if (Options != null)
                    hashCode = hashCode * 59 + Options.GetHashCode();
                    if (PassengerRefs != null)
                    hashCode = hashCode * 59 + PassengerRefs.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BaggageAllowanceItem left, BaggageAllowanceItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BaggageAllowanceItem left, BaggageAllowanceItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
