/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Disclosure description
    /// </summary>
    [DataContract]
    public partial class DisclosureDescription : IEquatable<DisclosureDescription>
    { 
        /// <summary>
        /// Category
        /// </summary>
        /// <value>Category</value>

        [DataMember(Name="category")]
        public string Category { get; set; }

        /// <summary>
        /// Item
        /// </summary>
        /// <value>Item</value>

        [DataMember(Name="item")]
        public string Item { get; set; }

        /// <summary>
        /// Gets or Sets Media
        /// </summary>

        [DataMember(Name="media")]
        public MediaData Media { get; set; }

        /// <summary>
        /// MetadataToken
        /// </summary>
        /// <value>MetadataToken</value>

        [DataMember(Name="metadataToken")]
        public string MetadataToken { get; set; }

        /// <summary>
        /// A reference to the origin-destination
        /// </summary>
        /// <value>A reference to the origin-destination</value>

        [DataMember(Name="originDestinationReference")]
        public string OriginDestinationReference { get; set; }

        /// <summary>
        /// Properties
        /// </summary>
        /// <value>Properties</value>

        [DataMember(Name="properties")]
        public List<DisclosureProperty> Properties { get; set; }

        /// <summary>
        /// Text
        /// </summary>
        /// <value>Text</value>

        [DataMember(Name="text")]
        public string Text { get; set; }

        /// <summary>
        /// Units
        /// </summary>
        /// <value>Units</value>

        [DataMember(Name="units")]
        public string Units { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DisclosureDescription {\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Item: ").Append(Item).Append("\n");
            sb.Append("  Media: ").Append(Media).Append("\n");
            sb.Append("  MetadataToken: ").Append(MetadataToken).Append("\n");
            sb.Append("  OriginDestinationReference: ").Append(OriginDestinationReference).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Units: ").Append(Units).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DisclosureDescription)obj);
        }

        /// <summary>
        /// Returns true if DisclosureDescription instances are equal
        /// </summary>
        /// <param name="other">Instance of DisclosureDescription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DisclosureDescription other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Category == other.Category ||
                    Category != null &&
                    Category.Equals(other.Category)
                ) && 
                (
                    Item == other.Item ||
                    Item != null &&
                    Item.Equals(other.Item)
                ) && 
                (
                    Media == other.Media ||
                    Media != null &&
                    Media.Equals(other.Media)
                ) && 
                (
                    MetadataToken == other.MetadataToken ||
                    MetadataToken != null &&
                    MetadataToken.Equals(other.MetadataToken)
                ) && 
                (
                    OriginDestinationReference == other.OriginDestinationReference ||
                    OriginDestinationReference != null &&
                    OriginDestinationReference.Equals(other.OriginDestinationReference)
                ) && 
                (
                    Properties == other.Properties ||
                    Properties != null &&
                    Properties.SequenceEqual(other.Properties)
                ) && 
                (
                    Text == other.Text ||
                    Text != null &&
                    Text.Equals(other.Text)
                ) && 
                (
                    Units == other.Units ||
                    Units != null &&
                    Units.Equals(other.Units)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Category != null)
                    hashCode = hashCode * 59 + Category.GetHashCode();
                    if (Item != null)
                    hashCode = hashCode * 59 + Item.GetHashCode();
                    if (Media != null)
                    hashCode = hashCode * 59 + Media.GetHashCode();
                    if (MetadataToken != null)
                    hashCode = hashCode * 59 + MetadataToken.GetHashCode();
                    if (OriginDestinationReference != null)
                    hashCode = hashCode * 59 + OriginDestinationReference.GetHashCode();
                    if (Properties != null)
                    hashCode = hashCode * 59 + Properties.GetHashCode();
                    if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                    if (Units != null)
                    hashCode = hashCode * 59 + Units.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DisclosureDescription left, DisclosureDescription right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DisclosureDescription left, DisclosureDescription right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
