/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Document : IEquatable<Document>
    { 
        /// <summary>
        /// Gets or Sets BirthCountry
        /// </summary>

        [DataMember(Name="birthCountry")]
        public string BirthCountry { get; set; }

        /// <summary>
        /// Gets or Sets DocumentID
        /// </summary>
        [Required]
        
        [DataMember(Name="documentID")]
        public string DocumentID { get; set; }

        /// <summary>
        /// Valid values: 
        /// </summary>
        /// <value>Valid values: </value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DocumentTypeEnum
        {
            
            /// <summary>
            /// Enum PPEnum for PP
            /// </summary>
            [EnumMember(Value = "PP")]
            PPEnum = 1,
            
            /// <summary>
            /// Enum NIEnum for NI
            /// </summary>
            [EnumMember(Value = "NI")]
            NIEnum = 2,
            
            /// <summary>
            /// Enum Empty for 
            /// </summary>
            [EnumMember(Value = "")]
            Empty = 3
        }

        /// <summary>
        /// Valid values: 
        /// </summary>
        /// <value>Valid values: </value>
        [Required]
        
        [DataMember(Name="documentType")]
        public DocumentTypeEnum? DocumentType { get; set; }

        /// <summary>
        /// The expiration date of the document using format YYYY-MM-DD.
        /// </summary>
        /// <value>The expiration date of the document using format YYYY-MM-DD.</value>

        [RegularExpression("/(\\d\\d\\d\\d)-(\\d\\d)-(\\d\\d)/")]
        [DataMember(Name="expirationDate")]
        public string ExpirationDate { get; set; }

        /// <summary>
        /// The date of issuance of the document using format YYYY-MM-DD.
        /// </summary>
        /// <value>The date of issuance of the document using format YYYY-MM-DD.</value>

        [RegularExpression("/(\\d\\d\\d\\d)-(\\d\\d)-(\\d\\d)/")]
        [DataMember(Name="issueDate")]
        public string IssueDate { get; set; }

        /// <summary>
        /// Gets or Sets ResidenceCountry
        /// </summary>

        [DataMember(Name="residenceCountry")]
        public string ResidenceCountry { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Document {\n");
            sb.Append("  BirthCountry: ").Append(BirthCountry).Append("\n");
            sb.Append("  DocumentID: ").Append(DocumentID).Append("\n");
            sb.Append("  DocumentType: ").Append(DocumentType).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  IssueDate: ").Append(IssueDate).Append("\n");
            sb.Append("  ResidenceCountry: ").Append(ResidenceCountry).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Document)obj);
        }

        /// <summary>
        /// Returns true if Document instances are equal
        /// </summary>
        /// <param name="other">Instance of Document to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Document other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BirthCountry == other.BirthCountry ||
                    BirthCountry != null &&
                    BirthCountry.Equals(other.BirthCountry)
                ) && 
                (
                    DocumentID == other.DocumentID ||
                    DocumentID != null &&
                    DocumentID.Equals(other.DocumentID)
                ) && 
                (
                    DocumentType == other.DocumentType ||
                    DocumentType != null &&
                    DocumentType.Equals(other.DocumentType)
                ) && 
                (
                    ExpirationDate == other.ExpirationDate ||
                    ExpirationDate != null &&
                    ExpirationDate.Equals(other.ExpirationDate)
                ) && 
                (
                    IssueDate == other.IssueDate ||
                    IssueDate != null &&
                    IssueDate.Equals(other.IssueDate)
                ) && 
                (
                    ResidenceCountry == other.ResidenceCountry ||
                    ResidenceCountry != null &&
                    ResidenceCountry.Equals(other.ResidenceCountry)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BirthCountry != null)
                    hashCode = hashCode * 59 + BirthCountry.GetHashCode();
                    if (DocumentID != null)
                    hashCode = hashCode * 59 + DocumentID.GetHashCode();
                    if (DocumentType != null)
                    hashCode = hashCode * 59 + DocumentType.GetHashCode();
                    if (ExpirationDate != null)
                    hashCode = hashCode * 59 + ExpirationDate.GetHashCode();
                    if (IssueDate != null)
                    hashCode = hashCode * 59 + IssueDate.GetHashCode();
                    if (ResidenceCountry != null)
                    hashCode = hashCode * 59 + ResidenceCountry.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Document left, Document right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Document left, Document right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
