/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OrderCreatePayload : IEquatable<OrderCreatePayload>
    { 
        /// <summary>
        /// CorporateID for corporate orders
        /// </summary>
        /// <value>CorporateID for corporate orders</value>

        [DataMember(Name="corporateID")]
        public string CorporateID { get; set; }

        /// <summary>
        /// Order metadata
        /// </summary>
        /// <value>Order metadata</value>

        [DataMember(Name="metas")]
        public Object Metas { get; set; }

        /// <summary>
        /// Gets or Sets Passengers
        /// </summary>
        [Required]
        
        [DataMember(Name="passengers")]
        public List<Passenger> Passengers { get; set; }

        /// <summary>
        /// Gets or Sets Payment
        /// </summary>

        [DataMember(Name="payment")]
        public Payment Payment { get; set; }

        /// <summary>
        /// The responseID provided in OfferPrice response
        /// </summary>
        /// <value>The responseID provided in OfferPrice response</value>
        [Required]
        
        [DataMember(Name="shoppingResponseID")]
        public string ShoppingResponseID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderCreatePayload {\n");
            sb.Append("  CorporateID: ").Append(CorporateID).Append("\n");
            sb.Append("  Metas: ").Append(Metas).Append("\n");
            sb.Append("  Passengers: ").Append(Passengers).Append("\n");
            sb.Append("  Payment: ").Append(Payment).Append("\n");
            sb.Append("  ShoppingResponseID: ").Append(ShoppingResponseID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OrderCreatePayload)obj);
        }

        /// <summary>
        /// Returns true if OrderCreatePayload instances are equal
        /// </summary>
        /// <param name="other">Instance of OrderCreatePayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderCreatePayload other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CorporateID == other.CorporateID ||
                    CorporateID != null &&
                    CorporateID.Equals(other.CorporateID)
                ) && 
                (
                    Metas == other.Metas ||
                    Metas != null &&
                    Metas.Equals(other.Metas)
                ) && 
                (
                    Passengers == other.Passengers ||
                    Passengers != null &&
                    Passengers.SequenceEqual(other.Passengers)
                ) && 
                (
                    Payment == other.Payment ||
                    Payment != null &&
                    Payment.Equals(other.Payment)
                ) && 
                (
                    ShoppingResponseID == other.ShoppingResponseID ||
                    ShoppingResponseID != null &&
                    ShoppingResponseID.Equals(other.ShoppingResponseID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CorporateID != null)
                    hashCode = hashCode * 59 + CorporateID.GetHashCode();
                    if (Metas != null)
                    hashCode = hashCode * 59 + Metas.GetHashCode();
                    if (Passengers != null)
                    hashCode = hashCode * 59 + Passengers.GetHashCode();
                    if (Payment != null)
                    hashCode = hashCode * 59 + Payment.GetHashCode();
                    if (ShoppingResponseID != null)
                    hashCode = hashCode * 59 + ShoppingResponseID.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(OrderCreatePayload left, OrderCreatePayload right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OrderCreatePayload left, OrderCreatePayload right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
