/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Passenger : IEquatable<Passenger>
    { 
        /// <summary>
        /// Gets or Sets Data
        /// </summary>

        [DataMember(Name="data")]
        public PassengerData Data { get; set; }

        /// <summary>
        /// Gets or Sets Document
        /// </summary>

        [DataMember(Name="document")]
        public Document Document { get; set; }

        /// <summary>
        /// FareBasisCodes
        /// </summary>
        /// <value>FareBasisCodes</value>

        [DataMember(Name="fareBasisCodes")]
        public Object FareBasisCodes { get; set; }

        /// <summary>
        /// Gets or Sets Identity4Discount
        /// </summary>

        [DataMember(Name="identity4Discount")]
        public List<Identity4Discount> Identity4Discount { get; set; }

        /// <summary>
        /// Infant reference (if any)
        /// </summary>
        /// <value>Infant reference (if any)</value>

        [DataMember(Name="infantReference")]
        public string InfantReference { get; set; }

        /// <summary>
        /// Gets or Sets PassengerType
        /// </summary>

        [DataMember(Name="passengerType")]
        public string PassengerType { get; set; }

        /// <summary>
        /// Gets or Sets Seats
        /// </summary>

        [DataMember(Name="seats")]
        public List<Seat> Seats { get; set; }

        /// <summary>
        /// Gets or Sets Services
        /// </summary>

        [DataMember(Name="services")]
        public List<ServiceRequest> Services { get; set; }

        /// <summary>
        /// Gets or Sets SpecialServices
        /// </summary>

        [DataMember(Name="specialServices")]
        public List<SSR> SpecialServices { get; set; }

        /// <summary>
        /// Traveler reference from ServiceList response
        /// </summary>
        /// <value>Traveler reference from ServiceList response</value>
        [Required]
        
        [DataMember(Name="travelerReference")]
        public string TravelerReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Passenger {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Document: ").Append(Document).Append("\n");
            sb.Append("  FareBasisCodes: ").Append(FareBasisCodes).Append("\n");
            sb.Append("  Identity4Discount: ").Append(Identity4Discount).Append("\n");
            sb.Append("  InfantReference: ").Append(InfantReference).Append("\n");
            sb.Append("  PassengerType: ").Append(PassengerType).Append("\n");
            sb.Append("  Seats: ").Append(Seats).Append("\n");
            sb.Append("  Services: ").Append(Services).Append("\n");
            sb.Append("  SpecialServices: ").Append(SpecialServices).Append("\n");
            sb.Append("  TravelerReference: ").Append(TravelerReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Passenger)obj);
        }

        /// <summary>
        /// Returns true if Passenger instances are equal
        /// </summary>
        /// <param name="other">Instance of Passenger to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Passenger other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Data == other.Data ||
                    Data != null &&
                    Data.Equals(other.Data)
                ) && 
                (
                    Document == other.Document ||
                    Document != null &&
                    Document.Equals(other.Document)
                ) && 
                (
                    FareBasisCodes == other.FareBasisCodes ||
                    FareBasisCodes != null &&
                    FareBasisCodes.Equals(other.FareBasisCodes)
                ) && 
                (
                    Identity4Discount == other.Identity4Discount ||
                    Identity4Discount != null &&
                    Identity4Discount.SequenceEqual(other.Identity4Discount)
                ) && 
                (
                    InfantReference == other.InfantReference ||
                    InfantReference != null &&
                    InfantReference.Equals(other.InfantReference)
                ) && 
                (
                    PassengerType == other.PassengerType ||
                    PassengerType != null &&
                    PassengerType.Equals(other.PassengerType)
                ) && 
                (
                    Seats == other.Seats ||
                    Seats != null &&
                    Seats.SequenceEqual(other.Seats)
                ) && 
                (
                    Services == other.Services ||
                    Services != null &&
                    Services.SequenceEqual(other.Services)
                ) && 
                (
                    SpecialServices == other.SpecialServices ||
                    SpecialServices != null &&
                    SpecialServices.SequenceEqual(other.SpecialServices)
                ) && 
                (
                    TravelerReference == other.TravelerReference ||
                    TravelerReference != null &&
                    TravelerReference.Equals(other.TravelerReference)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Data != null)
                    hashCode = hashCode * 59 + Data.GetHashCode();
                    if (Document != null)
                    hashCode = hashCode * 59 + Document.GetHashCode();
                    if (FareBasisCodes != null)
                    hashCode = hashCode * 59 + FareBasisCodes.GetHashCode();
                    if (Identity4Discount != null)
                    hashCode = hashCode * 59 + Identity4Discount.GetHashCode();
                    if (InfantReference != null)
                    hashCode = hashCode * 59 + InfantReference.GetHashCode();
                    if (PassengerType != null)
                    hashCode = hashCode * 59 + PassengerType.GetHashCode();
                    if (Seats != null)
                    hashCode = hashCode * 59 + Seats.GetHashCode();
                    if (Services != null)
                    hashCode = hashCode * 59 + Services.GetHashCode();
                    if (SpecialServices != null)
                    hashCode = hashCode * 59 + SpecialServices.GetHashCode();
                    if (TravelerReference != null)
                    hashCode = hashCode * 59 + TravelerReference.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Passenger left, Passenger right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Passenger left, Passenger right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
