/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PenaltyAmount : IEquatable<PenaltyAmount>
    { 
        /// <summary>
        /// The homogenised value of the penalty for the application case (35 or 30.65)
        /// </summary>
        /// <value>The homogenised value of the penalty for the application case (35 or 30.65)</value>

        [DataMember(Name="amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// The consumer currency of this value
        /// </summary>
        /// <value>The consumer currency of this value</value>

        [DataMember(Name="currency")]
        public string Currency { get; set; }

        /// <summary>
        /// The provider value of the penalty for the application case (30 or 30.70)
        /// </summary>
        /// <value>The provider value of the penalty for the application case (30 or 30.70)</value>

        [DataMember(Name="providerAmount")]
        public double? ProviderAmount { get; set; }

        /// <summary>
        /// The provider currency of this value
        /// </summary>
        /// <value>The provider currency of this value</value>

        [DataMember(Name="providerCurrency")]
        public string ProviderCurrency { get; set; }

        /// <summary>
        /// Penalty remark.
        /// </summary>
        /// <value>Penalty remark.</value>

        [DataMember(Name="remark")]
        public string Remark { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PenaltyAmount {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  ProviderAmount: ").Append(ProviderAmount).Append("\n");
            sb.Append("  ProviderCurrency: ").Append(ProviderCurrency).Append("\n");
            sb.Append("  Remark: ").Append(Remark).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PenaltyAmount)obj);
        }

        /// <summary>
        /// Returns true if PenaltyAmount instances are equal
        /// </summary>
        /// <param name="other">Instance of PenaltyAmount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PenaltyAmount other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                ) && 
                (
                    Currency == other.Currency ||
                    Currency != null &&
                    Currency.Equals(other.Currency)
                ) && 
                (
                    ProviderAmount == other.ProviderAmount ||
                    ProviderAmount != null &&
                    ProviderAmount.Equals(other.ProviderAmount)
                ) && 
                (
                    ProviderCurrency == other.ProviderCurrency ||
                    ProviderCurrency != null &&
                    ProviderCurrency.Equals(other.ProviderCurrency)
                ) && 
                (
                    Remark == other.Remark ||
                    Remark != null &&
                    Remark.Equals(other.Remark)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                    if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                    if (ProviderAmount != null)
                    hashCode = hashCode * 59 + ProviderAmount.GetHashCode();
                    if (ProviderCurrency != null)
                    hashCode = hashCode * 59 + ProviderCurrency.GetHashCode();
                    if (Remark != null)
                    hashCode = hashCode * 59 + Remark.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PenaltyAmount left, PenaltyAmount right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PenaltyAmount left, PenaltyAmount right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
