/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PriceDetailBreakdown : IEquatable<PriceDetailBreakdown>
    { 
        /// <summary>
        /// The base price, without any taxes (300 or 300.32)
        /// </summary>
        /// <value>The base price, without any taxes (300 or 300.32)</value>

        [DataMember(Name="base")]
        public double? Base { get; set; }

        /// <summary>
        /// The ID for each offer
        /// </summary>
        /// <value>The ID for each offer</value>

        [DataMember(Name="offerItemID")]
        public string OfferItemID { get; set; }

        /// <summary>
        /// Passenger references
        /// </summary>
        /// <value>Passenger references</value>

        [DataMember(Name="passengerRefs")]
        public string PassengerRefs { get; set; }

        /// <summary>
        /// The passenger type
        /// </summary>
        /// <value>The passenger type</value>

        [DataMember(Name="passengerType")]
        public string PassengerType { get; set; }

        /// <summary>
        /// The total sum of all surcharges (6 or 6.05)
        /// </summary>
        /// <value>The total sum of all surcharges (6 or 6.05)</value>

        [DataMember(Name="surcharge")]
        public double? Surcharge { get; set; }

        /// <summary>
        /// Gets or Sets Tax
        /// </summary>

        [DataMember(Name="tax")]
        public PriceDetailTax Tax { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PriceDetailBreakdown {\n");
            sb.Append("  Base: ").Append(Base).Append("\n");
            sb.Append("  OfferItemID: ").Append(OfferItemID).Append("\n");
            sb.Append("  PassengerRefs: ").Append(PassengerRefs).Append("\n");
            sb.Append("  PassengerType: ").Append(PassengerType).Append("\n");
            sb.Append("  Surcharge: ").Append(Surcharge).Append("\n");
            sb.Append("  Tax: ").Append(Tax).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PriceDetailBreakdown)obj);
        }

        /// <summary>
        /// Returns true if PriceDetailBreakdown instances are equal
        /// </summary>
        /// <param name="other">Instance of PriceDetailBreakdown to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PriceDetailBreakdown other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Base == other.Base ||
                    Base != null &&
                    Base.Equals(other.Base)
                ) && 
                (
                    OfferItemID == other.OfferItemID ||
                    OfferItemID != null &&
                    OfferItemID.Equals(other.OfferItemID)
                ) && 
                (
                    PassengerRefs == other.PassengerRefs ||
                    PassengerRefs != null &&
                    PassengerRefs.Equals(other.PassengerRefs)
                ) && 
                (
                    PassengerType == other.PassengerType ||
                    PassengerType != null &&
                    PassengerType.Equals(other.PassengerType)
                ) && 
                (
                    Surcharge == other.Surcharge ||
                    Surcharge != null &&
                    Surcharge.Equals(other.Surcharge)
                ) && 
                (
                    Tax == other.Tax ||
                    Tax != null &&
                    Tax.Equals(other.Tax)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Base != null)
                    hashCode = hashCode * 59 + Base.GetHashCode();
                    if (OfferItemID != null)
                    hashCode = hashCode * 59 + OfferItemID.GetHashCode();
                    if (PassengerRefs != null)
                    hashCode = hashCode * 59 + PassengerRefs.GetHashCode();
                    if (PassengerType != null)
                    hashCode = hashCode * 59 + PassengerType.GetHashCode();
                    if (Surcharge != null)
                    hashCode = hashCode * 59 + Surcharge.GetHashCode();
                    if (Tax != null)
                    hashCode = hashCode * 59 + Tax.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PriceDetailBreakdown left, PriceDetailBreakdown right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PriceDetailBreakdown left, PriceDetailBreakdown right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
