/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PriceDetail : IEquatable<PriceDetail>
    { 
        /// <summary>
        /// 670 or 670.41
        /// </summary>
        /// <value>670 or 670.41</value>

        [DataMember(Name="base")]
        public double? Base { get; set; }

        /// <summary>
        /// The price for each flight offer. There is an offer for each passenger (ADT, CHD, INF).
        /// </summary>
        /// <value>The price for each flight offer. There is an offer for each passenger (ADT, CHD, INF).</value>

        [DataMember(Name="breakdown")]
        public List<PriceDetailBreakdown> Breakdown { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>

        [DataMember(Name="currency")]
        public string Currency { get; set; }

        /// <summary>
        /// The surcharges for the whole flight offer (6 or 6.05).
        /// </summary>
        /// <value>The surcharges for the whole flight offer (6 or 6.05).</value>

        [DataMember(Name="surcharge")]
        public double? Surcharge { get; set; }

        /// <summary>
        /// Gets or Sets Tax
        /// </summary>

        [DataMember(Name="tax")]
        public PriceDetailTax Tax { get; set; }

        /// <summary>
        /// 720 or 720.62
        /// </summary>
        /// <value>720 or 720.62</value>

        [DataMember(Name="total")]
        public double? Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PriceDetail {\n");
            sb.Append("  Base: ").Append(Base).Append("\n");
            sb.Append("  Breakdown: ").Append(Breakdown).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Surcharge: ").Append(Surcharge).Append("\n");
            sb.Append("  Tax: ").Append(Tax).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PriceDetail)obj);
        }

        /// <summary>
        /// Returns true if PriceDetail instances are equal
        /// </summary>
        /// <param name="other">Instance of PriceDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PriceDetail other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Base == other.Base ||
                    Base != null &&
                    Base.Equals(other.Base)
                ) && 
                (
                    Breakdown == other.Breakdown ||
                    Breakdown != null &&
                    Breakdown.SequenceEqual(other.Breakdown)
                ) && 
                (
                    Currency == other.Currency ||
                    Currency != null &&
                    Currency.Equals(other.Currency)
                ) && 
                (
                    Surcharge == other.Surcharge ||
                    Surcharge != null &&
                    Surcharge.Equals(other.Surcharge)
                ) && 
                (
                    Tax == other.Tax ||
                    Tax != null &&
                    Tax.Equals(other.Tax)
                ) && 
                (
                    Total == other.Total ||
                    Total != null &&
                    Total.Equals(other.Total)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Base != null)
                    hashCode = hashCode * 59 + Base.GetHashCode();
                    if (Breakdown != null)
                    hashCode = hashCode * 59 + Breakdown.GetHashCode();
                    if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                    if (Surcharge != null)
                    hashCode = hashCode * 59 + Surcharge.GetHashCode();
                    if (Tax != null)
                    hashCode = hashCode * 59 + Tax.GetHashCode();
                    if (Total != null)
                    hashCode = hashCode * 59 + Total.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PriceDetail left, PriceDetail right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PriceDetail left, PriceDetail right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
