/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// SeatAvailability data
    /// </summary>
    [DataContract]
    public partial class SeatAvailabilityPayload : IEquatable<SeatAvailabilityPayload>
    { 
        /// <summary>
        /// AirGateway order ID
        /// </summary>
        /// <value>AirGateway order ID</value>

        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Passengers
        /// </summary>

        [DataMember(Name="passengers")]
        public List<Passenger> Passengers { get; set; }

        /// <summary>
        /// Segment ID. Use when need to fetch a certain segment of flight
        /// </summary>
        /// <value>Segment ID. Use when need to fetch a certain segment of flight</value>

        [DataMember(Name="segmentID")]
        public string SegmentID { get; set; }

        /// <summary>
        /// The responseID provided in OfferPrice response. Use when request SeatAvailability on Pre-Booking stage
        /// </summary>
        /// <value>The responseID provided in OfferPrice response. Use when request SeatAvailability on Pre-Booking stage</value>

        [DataMember(Name="shoppingResponseID")]
        public string ShoppingResponseID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SeatAvailabilityPayload {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Passengers: ").Append(Passengers).Append("\n");
            sb.Append("  SegmentID: ").Append(SegmentID).Append("\n");
            sb.Append("  ShoppingResponseID: ").Append(ShoppingResponseID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SeatAvailabilityPayload)obj);
        }

        /// <summary>
        /// Returns true if SeatAvailabilityPayload instances are equal
        /// </summary>
        /// <param name="other">Instance of SeatAvailabilityPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SeatAvailabilityPayload other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Passengers == other.Passengers ||
                    Passengers != null &&
                    Passengers.SequenceEqual(other.Passengers)
                ) && 
                (
                    SegmentID == other.SegmentID ||
                    SegmentID != null &&
                    SegmentID.Equals(other.SegmentID)
                ) && 
                (
                    ShoppingResponseID == other.ShoppingResponseID ||
                    ShoppingResponseID != null &&
                    ShoppingResponseID.Equals(other.ShoppingResponseID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Passengers != null)
                    hashCode = hashCode * 59 + Passengers.GetHashCode();
                    if (SegmentID != null)
                    hashCode = hashCode * 59 + SegmentID.GetHashCode();
                    if (ShoppingResponseID != null)
                    hashCode = hashCode * 59 + ShoppingResponseID.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SeatAvailabilityPayload left, SeatAvailabilityPayload right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SeatAvailabilityPayload left, SeatAvailabilityPayload right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
