/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TicketCouponAirlineInfo : IEquatable<TicketCouponAirlineInfo>
    { 
        /// <summary>
        /// Gets or Sets Arrival
        /// </summary>

        [DataMember(Name="arrival")]
        public FlightPointData Arrival { get; set; }

        /// <summary>
        /// Gets or Sets ArrivalDateTime
        /// </summary>

        [DataMember(Name="arrivalDateTime")]
        public TicketCouponAirlineInfoDepartureArrivalDateTime ArrivalDateTime { get; set; }

        /// <summary>
        /// Gets or Sets Departure
        /// </summary>

        [DataMember(Name="departure")]
        public FlightPointData Departure { get; set; }

        /// <summary>
        /// Gets or Sets DepartureDateTime
        /// </summary>

        [DataMember(Name="departureDateTime")]
        public TicketCouponAirlineInfoDepartureArrivalDateTime DepartureDateTime { get; set; }

        /// <summary>
        /// Gets or Sets Equipment
        /// </summary>

        [DataMember(Name="equipment")]
        public Equipment Equipment { get; set; }

        /// <summary>
        /// Gets or Sets MarketingCarrier
        /// </summary>

        [DataMember(Name="marketingCarrier")]
        public MarketingCarrier MarketingCarrier { get; set; }

        /// <summary>
        /// Flight Segment status
        /// </summary>
        /// <value>Flight Segment status</value>

        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TicketCouponAirlineInfo {\n");
            sb.Append("  Arrival: ").Append(Arrival).Append("\n");
            sb.Append("  ArrivalDateTime: ").Append(ArrivalDateTime).Append("\n");
            sb.Append("  Departure: ").Append(Departure).Append("\n");
            sb.Append("  DepartureDateTime: ").Append(DepartureDateTime).Append("\n");
            sb.Append("  Equipment: ").Append(Equipment).Append("\n");
            sb.Append("  MarketingCarrier: ").Append(MarketingCarrier).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TicketCouponAirlineInfo)obj);
        }

        /// <summary>
        /// Returns true if TicketCouponAirlineInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of TicketCouponAirlineInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TicketCouponAirlineInfo other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Arrival == other.Arrival ||
                    Arrival != null &&
                    Arrival.Equals(other.Arrival)
                ) && 
                (
                    ArrivalDateTime == other.ArrivalDateTime ||
                    ArrivalDateTime != null &&
                    ArrivalDateTime.Equals(other.ArrivalDateTime)
                ) && 
                (
                    Departure == other.Departure ||
                    Departure != null &&
                    Departure.Equals(other.Departure)
                ) && 
                (
                    DepartureDateTime == other.DepartureDateTime ||
                    DepartureDateTime != null &&
                    DepartureDateTime.Equals(other.DepartureDateTime)
                ) && 
                (
                    Equipment == other.Equipment ||
                    Equipment != null &&
                    Equipment.Equals(other.Equipment)
                ) && 
                (
                    MarketingCarrier == other.MarketingCarrier ||
                    MarketingCarrier != null &&
                    MarketingCarrier.Equals(other.MarketingCarrier)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Arrival != null)
                    hashCode = hashCode * 59 + Arrival.GetHashCode();
                    if (ArrivalDateTime != null)
                    hashCode = hashCode * 59 + ArrivalDateTime.GetHashCode();
                    if (Departure != null)
                    hashCode = hashCode * 59 + Departure.GetHashCode();
                    if (DepartureDateTime != null)
                    hashCode = hashCode * 59 + DepartureDateTime.GetHashCode();
                    if (Equipment != null)
                    hashCode = hashCode * 59 + Equipment.GetHashCode();
                    if (MarketingCarrier != null)
                    hashCode = hashCode * 59 + MarketingCarrier.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TicketCouponAirlineInfo left, TicketCouponAirlineInfo right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TicketCouponAirlineInfo left, TicketCouponAirlineInfo right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
